<?xml version="1.0"?>
<robot name="robot" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:property name="PI" value="3.1415926535897931"/>

  <xacro:property name="dummy_inertia" value="1e-09"/>

  <xacro:property name="mount_spacing" value="0.120"/>

  <material name="dark_grey"><color rgba="0.2 0.2 0.2 1.0"/></material>
  <material name="light_grey"><color rgba="0.4 0.4 0.4 1.0"/></material>
  <material name="stl"><color rgba="0.8 0.8 0.0 1.0"/></material>
  <material name="red"><color rgba="0.95 0.26 0.21 1.0"/></material>
  <material name="dark_red"><color rgba="0.5 0.0 0.0 1.0"/></material>
  <material name="black"><color rgba="0.15 0.15 0.15 1.0"/></material>
  <material name="green"><color rgba="0 1 0 1"/></material>
  <material name="invisible"><color rgba="0 0 0 0"/></material>



  <xacro:property name="chassis_height" value="0.136"/>
  <xacro:property name="chassis_width" value="0.4731"/>
  <xacro:property name="chassis_length" value="0.627"/>

  <xacro:property name="sled_hoz_width" value="0.442"/>
  <xacro:property name="sled_hoz_length" value="0.245"/>
  <xacro:property name="sled_hoz_height" value="0.0405"/>

  <xacro:property name="sled_ver_width" value="0.350"/>
  <xacro:property name="sled_ver_length" value="0.0405"/>
  <xacro:property name="sled_ver_height" value="0.425"/>

  <xacro:property name="arm_upper_width" value="0.429"/>
  <xacro:property name="arm_upper_length" value="0.452"/>
  <xacro:property name="arm_upper_height" value="0.0405"/>

  <xacro:property name="arm_angle" value="2.356194490192345"/> <!-- 135 degrees -->

  <xacro:property name="arm_lower_width" value="0.429"/>
  <xacro:property name="arm_lower_length" value="0.440"/>
  <xacro:property name="arm_lower_height" value="0.0405"/>

  <!-- TODO: measure these -->
  <xacro:property name="wheel_base" value="0.505"/>
  <xacro:property name="wheel_track" value="0.61"/>
  <xacro:property name="wheel_radius" value="0.145"/>
  <xacro:property name="wheel_width" value="0.125"/>
  <!-- not sure about this one -->
  <xacro:property name="wheel_height" value="0.047625"/>


  <xacro:macro name="wheel" params="prefix reflect *joint_pose">
    <link name="${prefix}_wheel_link">
      <visual>
        <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="black"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="8.6"/>
        <!-- moment of inertia of a cylinder https://en.wikipedia.org/wiki/List_of_moments_of_inertia#List_of_3D_inertia_tensors -->
        <inertia ixx="0.0785782304" ixy="0" ixz="0" iyy="0.0785782304" iyz="0" izz="0.1051404359"/>
        <!-- <inertia
          ixx="${(1.0/12.0)*8.6*(3*wheel_radius**2 + wheel_width**2)}" ixy="0" ixz="0"
          iyy="${(1.0/12.0)*8.6*(3*wheel_radius**2 + wheel_width**2)}" iyz="0"
          izz="${0.5*8.6*wheel_radius}"/> -->
      </inertial>
    </link>

    <gazebo reference="${prefix}_wheel_link">
      <!-- TODO: set these constants. They are just taken from urdf_tutorial. 09 -->
      <mu1 value="5"/>
      <mu2 value="5"/>
      <!-- <minDepth>0.00</minDepth> -->
      <!-- <max_vel>0.01</max_vel> -->
      <material>Gazebo/DarkGrey</material>
    </gazebo>

    <joint name="${prefix}_wheel" type="continuous">
      <parent link="chassis"/>
      <child link="${prefix}_wheel_link"/>
      <xacro:insert_block name="joint_pose"/>
      <axis xyz="0 ${reflect} 0"/>
      <!-- <dynamics damping="100" friction="1"/> -->
    </joint>

    <transmission name="${prefix}_wheel_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="${prefix}_wheel">
		  <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
      </joint>
      <actuator name="${prefix}_actuator">
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>
  </xacro:macro>

  <link name="base_link"></link>
  <joint name="chassis_base_joint" type="fixed">
    <parent link="base_link"/>
    <child link="chassis"/>
    <origin xyz="0 0 ${(chassis_height/2)+wheel_radius-wheel_height}"/>
  </joint>

  <link name="chassis">
    <visual>
      <origin xyz="0 0 0"/>
      <geometry>
          <mesh filename="package://robot_description/meshes/visual/chassis.dae"/>
      </geometry>
      <material name="red"/>
    </visual>
    <collision>
      <origin xyz="0 0 0"/>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="3.05"/>
      <inertia ixx="0.28" ixy="0.00" ixz="0.00" iyy="0.42" iyz="0.00" izz="0.17"/>
    </inertial>
  </link>

  <xacro:wheel prefix="left_front" reflect="1">
    <origin xyz="${wheel_base/2} ${wheel_track/2} 0" rpy="0 0 0"/>
  </xacro:wheel>
  <xacro:wheel prefix="left_rear" reflect="1">
      <origin xyz="${-wheel_base/2} ${wheel_track/2} 0" rpy="0 0 0"/>
  </xacro:wheel>
  <xacro:wheel prefix="right_front" reflect="-1">
      <origin xyz="${wheel_base/2} ${-wheel_track/2} 0" rpy="${PI} 0 0"/>
  </xacro:wheel>
  <xacro:wheel prefix="right_rear" reflect="-1">
    <origin xyz="${-wheel_base/2} ${-wheel_track/2} 0" rpy="${PI} 0 0"/>
  </xacro:wheel>

  <link name="sled_hoz">
    <visual>
      <geometry>
          <mesh filename="package://robot_description/meshes/visual/sled.dae"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <material name="light_grey"/>
    </visual>
    <collision>
      <origin xyz="0 0 0"/>
      <geometry>
        <box size="${sled_hoz_length} ${sled_hoz_width} ${sled_hoz_height}"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="3.0"/>

      <!-- izz="-0.28" iyy="1.00" iyz="-0.96" ixx="0.96" ixy="0. -->
    <inertia ixx="0.08" ixy="0.00" ixz="-0.01" iyy="0.06" iyz="0.00" izz="0.04"/>
    </inertial>
  </link>

  <joint name="sled_joint" type="prismatic">
    <parent link="chassis"/>
    <child link="sled_hoz"/>
    <axis rpy="0 0 0" xyz="1 0 0"/>
    <!-- <dynamics damping="0.1" friction="0"/> -->
    <dynamics damping="100" friction="1"/>
    <limit effort="1000" lower="${-(chassis_length/2)+(sled_hoz_length/2)-(sled_hoz_length/4)}" upper="${(chassis_length/2)-(sled_hoz_length/2)-(sled_hoz_length/4)}" velocity="0.1"/>
    <origin rpy="0 0 0" xyz="0 0 ${chassis_height/2 + sled_hoz_height/2}"/>
  </joint>

  <link name="sled_ver">
    <visual>
      <geometry>
        <!-- <box size="${sled_ver_length} ${sled_ver_width} ${sled_ver_height}"/> -->
        <box size="0.001 0.001 0.001"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <material name="light_grey"/>
    </visual>
    <collision>
      <origin xyz="0 0 0"/>
      <geometry>
        <box size="${sled_ver_length} ${sled_ver_width} ${sled_ver_height}"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="12.25"/>
      <inertia ixx="0.225942" ixy="-5.6e-5" ixz="0.041831" iyy="0.162776" iyz="4.5e-5" izz="0.312502"/>
    </inertial>
  </link>
  <joint name="sled_ver_joint" type="fixed">
    <parent link="sled_hoz"/>
    <child link="sled_ver"/>
    <origin rpy="0 0 0" xyz="${-sled_hoz_length/2 + sled_ver_length/2} 0 ${sled_ver_height/2 + sled_hoz_height/2}"/>
  </joint>


  <link name="arm_upper">
    <visual>
     <origin xyz="${arm_upper_length/2 - sled_ver_length/2} 0 0"/>
     <!-- <origin xyz="${arm_upper_length/2 + 0.005} 0 0.02"/> -->
      <geometry>
          <mesh filename="package://robot_description/meshes/visual/arms_visual.dae"/>
      </geometry>
      <material name="red"/>
    </visual>
    <collision>
      <!-- <origin xyz="${arm_upper_length/2 + 0.005} 0 0.02"/> -->
      <origin xyz="${arm_upper_length/2 - sled_ver_length/2} 0 0"/>
      <geometry>
        <box size="${arm_upper_length} ${arm_upper_width} ${arm_upper_height}"/>
      </geometry>
      <material name="red"/>
    </collision>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="2.5"/>
      <inertia ixx="0.04" ixz="-0.02" ixy="0.00" izz="0.07" iyz="0.0" iyy="0.05" />
      <!-- <inertia ixx="0.93" ixy="0.00" ixz="-0.37" iyy="-1.00" izz="0.93" /> -->
    </inertial>
  </link>

  <joint name="arm_joint" type="revolute">
    <parent link="sled_ver"/>
    <child link="arm_upper"/>
    <origin xyz="0 0 ${sled_ver_height/2}"/>
    <axis xyz="0 1 0"/>
    <limit lower="-0.8" upper="0.31" effort="1000000" velocity="0.1"/>
    <dynamics damping="0.1" friction="0"/>
  </joint>

  <link name="arm_lower">
    <visual>
     <origin xyz="0 0 0"/>
      <geometry>
        <box size="0.001 0.001 0.001"/>
      </geometry>
      <material name="red"/>
    </visual>

    <collision>
      <origin xyz="0 0 0"/>
      <geometry>
        <box size="${arm_lower_length} ${arm_lower_width} ${arm_lower_height}"/>
    </geometry>
    </collision>

    <inertial>
      <origin xyz="0.439315 0.004673 -0.035609" rpy="0 0 0"/>
      <mass value="0.01"/>
      <inertia ixx="${dummy_inertia}" ixy="0" ixz="0" iyy="${dummy_inertia}" iyz="0" izz="${dummy_inertia}" />
    </inertial>

  </link>

  <joint name="arm_lower_joint" type="fixed">
    <parent link="arm_upper"/>
    <child link="arm_lower"/>
    <origin xyz="${arm_upper_length/2 + arm_lower_length/sqrt(2) + sled_ver_length} 0 ${-arm_lower_length/sqrt(2)/2}" rpy="0 ${PI - arm_angle} 0"/>
  </joint>

<link name="bucket">

    <visual>
      <origin xyz="0.08 0 0.015"/>
      <geometry>
        <mesh filename="package://robot_description/meshes/visual/bucket_visual.dae"/>
      </geometry>
    </visual>

    <collision>
      <origin xyz="0.08 0 0.015"/>
      <geometry>
          <mesh filename="package://robot_description/meshes/visual/bucket.dae"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="2.45"/>
      <inertia ixx="0.19" ixy="0.0" ixz="0.00" iyy="0.03" iyz="0.00" izz="0.17"/>
    </inertial>

  </link>

  <joint name="bucket_joint" type="revolute">
    <parent link="arm_lower"/>
    <child link="bucket"/>
    <origin xyz="${arm_lower_length/sqrt(2) - 0.075} 0.0 -0.032"/>
    <axis xyz="0 1 0"/>
    <limit lower="${-1.693}" upper="${0.384}" effort="100000" velocity="1"/>
    <dynamics damping="0.1" friction="0"/>
  </joint>

  <link name="ZED_left_camera">
        <visual>
            <origin xyz="0 0 0" rpy="0 1.57 0"/>
            <geometry>
                <cylinder radius="0.007" length=".031"/>
            </geometry>
            <material name="dark_grey">
                <color rgba="0.1 0.1 0.1 1"/>
            </material>
        </visual>
    </link>
    <link name="ZED_center">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://robot_description/urdf/ZED.stl" />
            </geometry>
            <material name="light_grey">
                <color rgba="0.8 0.8 0.8 0.8"/>
            </material>
        </visual>
    </link>
    <link name="ZED_right_camera">
        <visual>
            <origin xyz="0 0 0" rpy="0 1.57 0"/>
            <geometry>
                <cylinder radius="0.007" length=".031"/>
            </geometry>
            <material name="dark_grey">
                <color rgba="0.1 0.1 0.1 1"/>
            </material>
        </visual>
    </link>

    <joint name="ZED_center_joint" type="fixed">
        <parent link="ZED_left_camera"/>
        <child link="ZED_center"/>
        <origin xyz="0 -0.06 0" rpy="0 0 0" />
    </joint>

    <joint name="ZED_right_camera_joint" type="fixed">
        <parent link="ZED_left_camera"/>
        <child link="ZED_right_camera"/>
        <origin xyz="0 -0.12 0" rpy="0 0 0" />
    </joint>

  <joint name="zed_joint" type="fixed">
    <parent link="arm_lower"/>
    <child link="ZED_left_camera"/>
    <origin rpy="0 ${-pi/4} 0" xyz="${-arm_lower_length/(1.2*sqrt(2))} 0.06775 0.0"/>
  </joint>

  <link name="imu_link">
    <inertial>
      <mass value="0.001"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="${dummy_inertia}" ixy="0.0" ixz="0.0" iyy="${dummy_inertia}" iyz="0.0" izz="${dummy_inertia}"/>
    </inertial>
  </link>
  <joint name="imu_joint" type="fixed">
    <parent link="chassis"/>
    <child link="imu_link"/>
  </joint>

  <!-- Bring in simulation configuration for Gazebo. -->
  <xacro:include filename="test.gazebo"/>

  <transmission name="sled_hoz_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="sled_joint">
		<hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="rack_and_pinion">
		<hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="arm_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="arm_joint">
		<hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="arm_linear_actuators">
		<hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="bucket_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="bucket_joint">
		<hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="bucket_linear_actuators">
		<hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

</robot>
